version: '3.8'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - docker/db.env

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  ruby-base: &ruby-base
    stdin_open: true
    tty: true
    volumes:
      - ev_gems:/usr/local/bundle/gems
      - ev_cache_rails:/app/tmp/cache
      - .:/app
    depends_on:
      - db
      - redis
    build: .
    env_file:
      - docker/db.env
      - docker/sidekiq.env
      - docker/ev.env

  sidekiq:
    <<: *ruby-base
    command: bundle exec sidekiq
    volumes:
      - sidekiq_gems:/usr/local/bundle/gems
      - sidekiq_cache_rails:/app/tmp/cache
      - .:/app

  ev:
    <<: *ruby-base
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}"
    ports:
      - 3000:3000
    depends_on:
      - sidekiq
    volumes:
      - ev_gems:/usr/local/bundle/gems
      - ev_cache_rails:/app/tmp/cache
      - .:/app

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ev.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ev
    env_file:
      - docker/ev.env
      - docker/nginx.env

volumes:
  redis:
  postgres:
  ev_gems:
  ev_cache_rails:
  sidekiq_cache_rails:
  sidekiq_gems:
